name: meal_saver_phone
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  image_picker: ^1.1.2
  image_cropper: ^9.0.0
  shared_preferences: ^2.5.2
  stomp_dart_client: ^2.1.3
  web_socket_channel: ^3.0.2
  flutter_local_notifications: ^19.0.0
  permission_handler: ^12.0.0+1
  app_links: ^6.4.0
  intl: ^0.20.2
  material_design_icons_flutter: ^7.0.7296
  path: ^1.8.3
  crop_your_image: 0.7.5
  video_player: ^2.9.5
  html_unescape: ^2.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/videos/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Italic.ttf
          style: italic
